[package]
name = "dxcore-rs"
version = "0.1.0"
edition = "2024"

[features]
integration = []

[dependencies]
ibapi = { git = "https://github.com/rzimmerdev/rust-ibapi", features = [
  "sync",
], default-features = false }
futures = { version = "0.3", default-features = false, features = ["std"] }
dotenvy = "0.15"
polars = { version = "0.46", features = ["dtype-date", "strings"] }

[[example]]
name = "strategy"
path = "demo/strategy.rs"
