"""Type stubs for the `dxcore` package.

Hand-written; keep in sync with `crates/pybindings/src`. The compiled
extension module carries no type information, so type checkers resolve
the package namespace through these files.
"""

from .core import AccountMetric, Instrument, InstrumentStore, Portfolio
from .interface import (
    Contract,
    FmpBalanceSheet,
    FmpClient,
    FmpIncomeStatement,
    FmpProfile,
    GuardianArticle,
    GuardianArticleBody,
    GuardianBlock,
    GuardianClient,
    HttpAccessor,
    IbkrInterface,
    Interface,
    InterfaceFactory,
    ServiceSpec,
    StrategyInterface,
    XbrlClient,
    XbrlFiling,
)
from .network import (
    Endpoint,
    FunctionalService,
    HttpServer,
    MeshService,
    Protocol,
    Registration,
    ServerHandle,
    ServiceError,
)
from .trading import (
    AsyncExecutor,
    BaseOrderEngine,
    DailyView,
    Executor,
    Order,
    OrderData,
    OrderPrice,
    OrderQuantity,
    OrderType,
    RunIterator,
    Side,
    Signal,
)

__all__ = [
    "AccountMetric",
    "AsyncExecutor",
    "BaseOrderEngine",
    "Contract",
    "DailyView",
    "Endpoint",
    "Executor",
    "FmpBalanceSheet",
    "FmpClient",
    "FmpIncomeStatement",
    "FmpProfile",
    "FunctionalService",
    "GuardianArticle",
    "GuardianArticleBody",
    "GuardianBlock",
    "GuardianClient",
    "HttpAccessor",
    "HttpServer",
    "IbkrInterface",
    "Instrument",
    "InstrumentStore",
    "Interface",
    "InterfaceFactory",
    "MeshService",
    "Order",
    "OrderData",
    "OrderPrice",
    "OrderQuantity",
    "OrderType",
    "Portfolio",
    "Protocol",
    "Registration",
    "RunIterator",
    "ServerHandle",
    "ServiceError",
    "ServiceSpec",
    "Side",
    "Signal",
    "StrategyInterface",
    "XbrlClient",
    "XbrlFiling",
]
