class Instrument:
    def __init__(
        self,
        contract_id: int,
        symbol: str,
        security_type: str,
        exchange: str,
        currency: str,
    ) -> None: ...
    @property
    def contract_id(self) -> int: ...
    @property
    def symbol(self) -> str: ...
    @property
    def security_type(self) -> str: ...
    @property
    def exchange(self) -> str: ...
    @property
    def currency(self) -> str: ...


class AccountMetric:
    def __init__(self, key: str, value: str, currency: str) -> None: ...
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def currency(self) -> str: ...


class Portfolio:
    def __init__(self) -> None: ...
    def upsert_metric(self, key: str, value: str, currency: str) -> None: ...
    def set_holding(self, instrument: Instrument, quantity: float) -> None: ...
    def instrument(self, contract_id: int) -> Instrument | None: ...
    def quantity(self, contract_id: int) -> float | None: ...
    def holding_count(self) -> int: ...
    def holdings(self) -> list[tuple[Instrument, float]]: ...
    def metrics(self) -> list[AccountMetric]: ...


class InstrumentStore:
    def __init__(self) -> None: ...
    def insert(self, instrument: Instrument) -> None: ...
    def get(self, contract_id: int) -> Instrument | None: ...
    def get_by_symbol(self, symbol: str) -> Instrument | None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
