import polars as pl

from .core import Portfolio


class FmpClient:
    def __init__(self, api_key: str) -> None: ...
    @staticmethod
    def from_env() -> FmpClient: ...
    def profile(self, symbol: str) -> FmpProfile: ...
    def balance_sheet(self, symbol: str) -> list[FmpBalanceSheet]: ...
    def income_statement(self, symbol: str) -> list[FmpIncomeStatement]: ...


class FmpProfile:
    @property
    def symbol(self) -> str: ...
    @property
    def price(self) -> float | None: ...
    @property
    def market_cap(self) -> float | None: ...
    @property
    def currency(self) -> str | None: ...


class FmpBalanceSheet:
    @property
    def symbol(self) -> str: ...
    @property
    def date(self) -> str: ...
    @property
    def period(self) -> str: ...
    @property
    def total_assets(self) -> float | None: ...
    @property
    def total_liabilities(self) -> float | None: ...
    @property
    def total_stockholders_equity(self) -> float | None: ...
    @property
    def total_equity(self) -> float | None: ...


class FmpIncomeStatement:
    @property
    def symbol(self) -> str: ...
    @property
    def date(self) -> str: ...
    @property
    def period(self) -> str: ...
    @property
    def revenue(self) -> float | None: ...
    @property
    def operating_income(self) -> float | None: ...
    @property
    def net_income(self) -> float | None: ...
    @property
    def weighted_average_shs_out(self) -> float | None: ...


class GuardianClient:
    def __init__(self, api_key: str) -> None: ...
    def search(self, query: str, page_size: int = 10) -> list[GuardianArticle]: ...
    def get_article(self, id: str) -> GuardianArticleBody: ...


class GuardianArticle:
    @property
    def id(self) -> str: ...
    @property
    def article_type(self) -> str: ...
    @property
    def section_id(self) -> str | None: ...
    @property
    def section_name(self) -> str | None: ...
    @property
    def web_publication_date(self) -> str: ...
    @property
    def web_title(self) -> str: ...
    @property
    def web_url(self) -> str: ...
    @property
    def api_url(self) -> str: ...
    @property
    def pillar_name(self) -> str | None: ...


class GuardianBlock:
    @property
    def id(self) -> str: ...
    @property
    def body_html(self) -> str: ...
    @property
    def body_text_summary(self) -> str: ...


class GuardianArticleBody:
    @property
    def id(self) -> str: ...
    @property
    def web_publication_date(self) -> str: ...
    @property
    def web_title(self) -> str: ...
    @property
    def web_url(self) -> str: ...
    @property
    def blocks(self) -> list[GuardianBlock]: ...


class XbrlClient:
    def __init__(self) -> None: ...
    def query_filings(self, queries: list[str], limit: int) -> list[XbrlFiling]: ...


class XbrlFiling:
    @property
    def entity_name(self) -> str: ...
    @property
    def language(self) -> str: ...
    @property
    def country(self) -> str: ...
    @property
    def period_end(self) -> str: ...
    @property
    def date_added(self) -> str: ...
    @property
    def view_url(self) -> str: ...


class Contract:
    def __init__(
        self,
        contract_id: int,
        symbol: str,
        security_type: str = "STK",
        exchange: str = "SMART",
        currency: str = "USD",
    ) -> None: ...
    @property
    def contract_id(self) -> int: ...
    @property
    def symbol(self) -> str: ...
    @property
    def security_type(self) -> str: ...
    @property
    def exchange(self) -> str: ...
    @property
    def currency(self) -> str: ...


class IbkrInterface:
    def __init__(self, host: str, client_id: int) -> None: ...
    def market_history(
        self, contract: Contract, bar_size: str, duration: str
    ) -> pl.DataFrame: ...
    def portfolio(self, account_id: str) -> Portfolio: ...
