from typing import ClassVar


class ServiceError(Exception): ...


class Protocol:
    Http: ClassVar[Protocol]
    @classmethod
    def parse(cls, name: str) -> Protocol | None: ...
    def __str__(self) -> str: ...


class Endpoint:
    @property
    def protocols(self) -> list[Protocol]: ...
    @property
    def description(self) -> str | None: ...


class Registration:
    @property
    def name(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def protocols(self) -> list[Protocol]: ...
    @property
    def endpoints(self) -> dict[str, Endpoint]: ...


# A service implements `call(request: dict) -> dict` returning {"value": ...};
# `name() -> str` and `endpoints() -> list[str]` are optional.
class HttpServer:
    def __init__(self, addr: str, service: object) -> None: ...
    def addr(self) -> str: ...
    def spawn(self) -> ServerHandle: ...


class ServerHandle:
    def addr(self) -> str: ...
    def stop(self) -> None: ...


class MeshService:
    def __init__(self) -> None: ...
    def register(self, service: object, url: str, protocol: Protocol) -> str: ...
    def registrations(self) -> dict[str, Registration]: ...
