from typing import ClassVar


class ServiceError(Exception): ...


class Protocol:
    Http: ClassVar[Protocol]
    @classmethod
    def parse(cls, name: str) -> Protocol | None: ...
    def __str__(self) -> str: ...


class Endpoint:
    @property
    def protocols(self) -> list[Protocol]: ...
    @property
    def description(self) -> str | None: ...


class Registration:
    @property
    def name(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def protocols(self) -> list[Protocol]: ...
    @property
    def endpoints(self) -> dict[str, Endpoint]: ...


# A service implements `call(request: dict) -> dict` returning {"value": ...};
# `name() -> str` and `endpoints() -> list[str]` are optional.
class HttpServer:
    def __init__(self, addr: str, service: object) -> None: ...
    def addr(self) -> str: ...
    def spawn(self) -> ServerHandle: ...


# A named bag of endpoints: get endpoints back reads, set endpoints writes;
# each handler takes the request arguments and returns a JSON-serializable
# value (Signal and OrderData included).
class FunctionalService:
    def __init__(self, name: str) -> None: ...
    def get(self, method: str, handler: object) -> FunctionalService: ...
    def set(self, method: str, handler: object) -> FunctionalService: ...
    def name(self) -> str: ...
    def endpoints(self) -> list[str]: ...


class ServerHandle:
    def addr(self) -> str: ...
    def stop(self) -> None: ...


class MeshService:
    def __init__(self) -> None: ...
    def register(self, service: object, url: str, protocol: Protocol) -> str: ...
    def registrations(self) -> dict[str, Registration]: ...
