name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - c_compiler: gcc
            cpp_compiler: g++
            build_type: Release

    steps:
      - uses: actions/checkout@v5

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build python3-venv python3-pip python3-dev

      - name: Setup Python virtual environment
        run: |
          python3 -m venv $HOME/venv_dxcore
          source $HOME/venv_dxcore/bin/activate
          pip install --upgrade pip
          pip install conan

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan2/
          key: conan-cache-${{ runner.os }}-${{ hashFiles('**/conandata.yml', '**/conanfile.py') }}
          restore-keys: |
            conan-cache-${{ runner.os }}-

      - name: Setup Conan and install dependencies
        shell: bash
        run: |
          source $HOME/venv_dxcore/bin/activate
          conan profile detect --force
          conan install . --profile default --build=missing

      - name: Configure CMake
        shell: bash
        run: |
          source $HOME/venv_dxcore/bin/activate
          cmake -B build \
                -G Ninja \
                -DCMAKE_MAKE_PROGRAM=$(which ninja) \
                -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
                -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -S ${{ github.workspace }}

      - name: Build source and bindings
        shell: bash
        run: |
          source $HOME/venv_dxcore/bin/activate
          cmake --build build --target dxcore --config ${{ matrix.build_type }}
          cmake --build build --target python --config ${{ matrix.build_type }}
          pip install --upgrade build scikit-build-core pybind11 cmake
          python -m build --no-isolation

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/

      - name: Upload Python interface
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  publish:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      id-token: write

    environment:
      name: publish

    steps:
      - name: Retrieve release distributions
        if: ${{ !env.ACT }}
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        if: ${{ !env.ACT }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/