name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  build:
    if: github.event_name != 'release'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build python3-venv python3-pip python3-dev

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.conan2/
#            ~/.conan2/profiles
          key: conan-cache-${{ runner.os }}-${{ hashFiles('**/conandata.yml', '**/conanfile.py') }}
          restore-keys: |
            conan-cache-${{ runner.os }}-

      - name: Setup Python virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install conan

      - name: Setup Conan
        shell: bash
        run: |
          source venv/bin/activate
          conan profile detect --force
          conan install . --profile default --build=missing

      - name: Set build output directory
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        shell: bash
        run: |
          source venv/bin/activate
          cmake -B ${{ steps.strings.outputs.build-output-dir }} \
                -G Ninja \
                -DCMAKE_MAKE_PROGRAM=$(which ninja) \
                -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
                -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -S ${{ github.workspace }}

      - name: Build source and bindings
        shell: bash
        run: |
          source venv/bin/activate
          cmake --build ${{ steps.strings.outputs.build-output-dir }} --target dxcore --config ${{ matrix.build_type }}
          cmake --build ${{ steps.strings.outputs.build-output-dir }} --target python --config ${{ matrix.build_type }}

  interface-build:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.conan2/
          #            ~/.conan2/profiles
          key: conan-cache-${{ runner.os }}-${{ hashFiles('**/conandata.yml', '**/conanfile.py') }}
          restore-keys: |
            conan-cache-${{ runner.os }}-

      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Setup Python virtual environment and install dependencies
        shell: bash
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install conan build

      - name: Setup Conan profile
        shell: bash
        run: |
          source venv/bin/activate
          conan profile detect --force

      - name: Build distributions
        shell: bash
        run: |
          source venv/bin/activate
          python -m build

      - name: Upload distributions
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  publish:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs:
      - interface-build
    permissions:
      id-token: write

    environment:
      name: publish

    steps:
      - name: Retrieve release distributions
        if: ${{ !env.ACT }}
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        if: ${{ !env.ACT }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/